### ISSUE TITLE
Set up Docker image?

### ISSUE THREAD

**Issue by thomaspaulin** [AucklandRobotics/MRR-Website#4]
Thoughts @matthewAURA? May be too much of a learning curve to Docker for a project of this scale.

**Comment by matthewAURA** [comment]
Docker would be great, though until we start deploying this somewhere the motivation is low. If we want to get a local dev environment setup with persistence, docker-compose is useful for setting up the app and the database.

**Comment by matthewAURA** [comment]
Deployments to Heroku using docker are setup in #9
